version: 2
updates:
- package-ecosystem: composer
  directory: "/"
  schedule:
    interval: daily
    time: "11:00"
  open-pull-requests-limit: 10
  versioning-strategy: increase
  ignore:
  - dependency-name: psr/container
    versions:
    - 1.1.0
  - dependency-name: swiftmailer/swiftmailer
    versions:
    - 6.2.5
    - 6.2.6
